---
title: "Real Property Tax in Baltimore"
subtitle: "Flaws in the current SDAT assessments of land"
author: "Joshua Spokes"
---

```{r pull-city-data, cache = TRUE}
# Load necessary libraries
library(httr)
library(jsonlite)
library(sf)
library(pbapply)
library(stringr)
library(dplyr)
library(NISTunits)
library(units)

# I am so angry that this works
baltimore <- st_read("https://geodata.baltimorecity.gov/egis/rest/services/CityView/Realproperty_OB/FeatureServer/0/query?returnGeometry=true&where=1=1&outFields=*&f=geojson")

baltimore_valid <- st_make_valid(baltimore)

mutate(baltimore_valid,
       total_assessed_value = CURRLAND + CURRIMPR + LANDEXMP + IMPREXMP,
       area_acres = set_units(st_area(geometry), acres),
       area_ft_sq = set_units(st_area(geometry), ft^2),
       valueperacre = total_assessed_value / area_acres,
       landvaluepsf = (CURRLAND + LANDEXMP) / area_ft_sq) -> baltimore_areas
```

```{r initial analysis}
initial_analysis_sample = c("1783017A",
                            "1783017",
                            "1784040",
                            "1784036",
                            "1784035",
                            "1784034",
                            "1784033",
                            "1784032",
                            "1784031",
                            "1784030",
                            "1784029",
                            "1784028",
                            "1784027",
                            "1784026",
                            "1784025",
                            "1784024",
                            "1784023",
                            "1784022",
                            "1784021",
                            "1784020",
                            "1784019",
                            "1784018",
                            "1784017",
                            "1784016",
                            "1784061",
                            "1784060",
                            "1784059",
                            "1784058",
                            "1784057",
                            "1784056",
                            "1784055",
                            "1784054",
                            "1784053",
                            "1784052")

filter(baltimore_areas,
       PIN %in% initial_analysis_sample) -> initial_analysis_lots

filter(initial_analysis_lots,
       str_detect(PIN, "^1783")) -> bk_rofo_block

rofo_vpa <- sum(bk_rofo_block$total_assessed_value) / sum(bk_rofo_block$area_acres)
rofo_prop_tax <- sum(bk_rofo_block$CITY_TAX)
rofo_land_value_psf <- sum(bk_rofo_block$CURRLAND) / sum(bk_rofo_block$area_ft_sq)

filter(initial_analysis_lots,
       str_detect(PIN, "^1784")) |>
  mutate(land_psf = CURRLAND / area_ft_sq) -> patterson_block

patterson_vpa <- sum(patterson_block$total_assessed_value) / sum(patterson_block$area_acres)
patterson_prop_tax <- sum(patterson_block$CITY_TAX)
patterson_land_value_psf <- sum(patterson_block$CURRLAND) / sum(patterson_block$area_ft_sq)

patterson_vpa

```

```{r two-block-city}
filter(baltimore_areas,
       BLOCK %in% c("1783 ", "1784 ")) -> two_block_city

slice_max(two_block_city, landvaluepsf, n = 5) |>
 arrange(desc(landvaluepsf)) |>
  select(FULLADDR, total_assessed_value, area_ft_sq, area_acres, landvaluepsf, valueperacre) -> highest_assessed_land

highest_assessed_land

slice_min(two_block_city, landvaluepsf, n = 5) |>
 arrange(desc(landvaluepsf)) |>
  select(FULLADDR, total_assessed_value, area_ft_sq, area_acres, landvaluepsf, valueperacre) -> lowest_assessed_land

lowest_assessed_land

library(tmap)

tmap_mode("view")

tm_basemap(leaflet::providers$OpenStreetMap) +
tm_shape(two_block_city) + 
  tm_polygons(border.col = "black") +
tm_shape(lowest_assessed_land) +
  tm_polygons(col = "red") +
tm_shape(highest_assessed_land) +
  tm_polygons(col = "green")

```



